/**
 * 音乐数据 — Mock 模拟数据（后端实现后可删除此文件）
 * 后端不可用时作为降级方案，确保前端 UI 有数据展示
 */
import type { Song, Playlist } from '@/types/music'

/** Mock 歌曲数据（后端实现后删除） */
export function getMockSongs(): Song[] {
  return [
    {
      id: 'mock_1',
      title: 'River Flows In You',
      artist: 'Yiruma',
      album: 'First Love',
      coverUrl: '',
      audioUrl: '',
      duration: 187,
      genres: ['piano', 'new-age'],
      emotion: 'calm',
      bpm: 65,
      year: 2001,
      source: 'local',
      externalId: null,
      reason: '宁静的钢琴曲，适合深夜放松心情',
    },
    {
      id: 'mock_2',
      title: '晴天',
      artist: '周杰伦',
      album: '叶惠美',
      coverUrl: '',
      audioUrl: '',
      duration: 269,
      genres: ['pop', 'mandopop'],
      emotion: 'melancholic',
      bpm: 72,
      year: 2003,
      source: 'local',
      externalId: null,
      reason: '怀旧的校园民谣风，勾起青春回忆',
    },
    {
      id: 'mock_3',
      title: 'Clair de Lune',
      artist: 'Claude Debussy',
      album: 'Suite Bergamasque',
      coverUrl: '',
      audioUrl: '',
      duration: 300,
      genres: ['classical', 'impressionist'],
      emotion: 'calm',
      bpm: 55,
      year: 1905,
      source: 'local',
      externalId: null,
      reason: '印象派经典，仿佛月光洒落',
    },
    {
      id: 'mock_4',
      title: 'Lose Yourself',
      artist: 'Eminem',
      album: '8 Mile Soundtrack',
      coverUrl: '',
      audioUrl: '',
      duration: 326,
      genres: ['hip-hop', 'rap'],
      emotion: 'energetic',
      bpm: 171,
      year: 2002,
      source: 'local',
      externalId: null,
      reason: '充满力量的节奏，锻炼时的最佳拍档',
    },
    {
      id: 'mock_5',
      title: 'Shape of My Heart',
      artist: 'Sting',
      album: 'Ten Summoner\'s Tales',
      coverUrl: '',
      audioUrl: '',
      duration: 278,
      genres: ['rock', 'soft-rock'],
      emotion: 'melancholic',
      bpm: 84,
      year: 1993,
      source: 'local',
      externalId: null,
      reason: '低沉的嗓音，深夜独自思考时的伴侣',
    },
    {
      id: 'mock_6',
      title: 'Summer',
      artist: 'Joe Hisaishi',
      album: 'Spirited Away OST',
      coverUrl: '',
      audioUrl: '',
      duration: 239,
      genres: ['soundtrack', 'orchestral'],
      emotion: 'happy',
      bpm: 120,
      year: 2001,
      source: 'local',
      externalId: null,
      reason: '轻快的管弦乐，让周末清晨充满活力',
    },
  ]
}

/** Mock 歌单数据（后端实现后删除） */
export function getMockPlaylists(): Playlist[] {
  const mockSongs = getMockSongs()

  return [
    {
      id: 'pl_1',
      name: '深夜电台 - 治愈时光',
      description: '深夜11点，让温柔的旋律陪你入睡',
      coverUrl: '',
      songs: [mockSongs[0], mockSongs[2], mockSongs[4]],
      scenario: 'lateNight',
      generatedBy: 'ai',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'pl_2',
      name: '专注时刻 - 沉浸工作',
      description: '适合深度工作的轻音乐',
      coverUrl: '',
      songs: [mockSongs[0], mockSongs[2], mockSongs[5]],
      scenario: 'focus',
      generatedBy: 'ai',
      createdAt: new Date().toISOString(),
    },
    {
      id: 'pl_3',
      name: '活力清晨 - 唤醒身体',
      description: '用节奏感十足的音乐开启新的一天',
      coverUrl: '',
      songs: [mockSongs[3], mockSongs[5], mockSongs[1]],
      scenario: 'morning',
      generatedBy: 'ai',
      createdAt: new Date().toISOString(),
    },
  ]
}
